#ifndef _ITEM_SUFFIX_H_
#define _ITEM_SUFFIX_H_

#define ITEM_SUFFIX_COUNT 674
const char *Suffix[ITEM_SUFFIX_COUNT] = 
{
	"",
	"of Health",
	"of Protection",
	"of Absorption",
	"of Life",
	"of Anima",
	"of Life Everlasting",
	"of Warding",
	"of the Sentinel",
	"of Guarding",
	"of Negation",
	"of Avoidance",
	"of Ducking",
	"of Evasion",
	"of Elusion",
	"of Piercing",
	"of Puncturing",
	"of Bashing",
	"of Bashing",
	"of Dummy",
	"of Thorns",
	"of Spikes",
	"of Razors",
	"of Swords",
	"of Readiness",
	"of Alacrity",
	"of Swiftness",
	"of Quickness",
	"of Blocking",
	"of Deflecting",
	"of the Apprentice",
	"of the Magus",
	"of the Magus",
	"of Frost",
	"of the Icicle",
	"of the Glacier",
	"of Winter",
	"of the Iceburg",
	"of Flame",
	"of Fire",
	"of Burning",
	"of Incineration",
	"of Wildfire",
	"of Shock",
	"of Lightning",
	"of Thunder",
	"of Storms",
	"of Arcing",
	"of Blight",
	"of Venom",
	"of Pestilence",
	"of Anthrax",
	"of Toxin",
	"of Worth",
	"of Measure",
	"of Excellence",
	"of Performance",
	"of Transcendence",
	"of Craftsmanship",
	"of Quality",
	"of Maiming",
	"of Slaying",
	"of Gore",
	"of Carnage",
	"of Slaughter",
	"of Butchery",
	"of Evisceration",
	"of Remedy",
	"of Amelioration",
	"of Defiance",
	"of Warmth",
	"of Balance",
	"of Equilibrium",
	"of Stability",
	"of Pacing",
	"of Haste",
	"of Speed",
	"of Acceleration",
	"of Traveling",
	"of Regeneration",
	"of Regrowth",
	"of Revivification",
	"of Vileness",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Riches",
	"of Ease",
	"of Simplicity",
	"of Alleviation",
	"of the Bear",
	"of Light",
	"of Radiance",
	"of the Sun",
	"of the Jackal",
	"of the Fox",
	"of the Wolf",
	"of the Tiger",
	"of the Mammoth",
	"of the Colossus",
	"of the Squid",
	"of the Whale",
	"of the Leech",
	"of the Locust",
	"of the Lamprey",
	"of the Bat",
	"of the Wraith",
	"of the Vampire",
	"of Strength",
	"of Might",
	"of the Ox",
	"of the Giant",
	"of the Titan",
	"of Atlus",
	"of Dexterity",
	"of Skill",
	"of Accuracy",
	"of Precision",
	"of Perfection",
	"of Nirvana",
	"of Energy",
	"of the Mind",
	"of Brilliance",
	"of Sorcery",
	"of Wizardry",
	"of Enlightenment",
	"of Shielding",
	"of Shielding",
	"of Shielding",
	"of Shielding",
	"of Self-Repair",
	"of Fast Repair",
	"of Replenishing",
	"of Propogation",
	"of Ages",
	"of the Kraken",
	"of Memory",
	"of the Elephant",
	"of Power",
	"of Grace",
	"of Grace and Power",
	"of the Yeti",
	"of the Phoenix",
	"of the Efreeti",
	"of the Cobra",
	"of the Elements",
	"of the Saint",
	"of the Heavens",
	"of the Arctic",
	"of Fire Ball",
	"of Fire Ball",
	"of Fire Ball",
	"of Fire Ball",
	"of Fire Ball",
	"of Lightning",
	"of Lightning",
	"of Lightning",
	"of Lightning",
	"of Lightning",
	"of Chain Lightning",
	"of Chain Lightning",
	"of Chain Lightning",
	"of Chain Lightning",
	"of Chain Lightning",
	"of Glacial Spike",
	"of Glacial Spike",
	"of Glacial Spike",
	"of Glacial Spike",
	"of Glacial Spike",
	"of Frozen Orb",
	"of Frozen Orb",
	"of Frozen Orb",
	"of Frozen Orb",
	"of Frozen Orb",
	"of Icebolt",
	"of Icebolt",
	"of Icebolt",
	"of Icebolt",
	"of Icebolt",
	"of Immolation",
	"of Immolation",
	"of Immolation",
	"of Immolation",
	"of Immolation",
	"of Meteor",
	"of Meteor",
	"of Meteor",
	"of Meteor",
	"of Meteor",
	"of Blizzard",
	"of Blizzard",
	"of Blizzard",
	"of Blizzard",
	"of Blizzard",
	"of Damage Amplification",
	"of Damage Amplification",
	"of Damage Amplification",
	"of Damage Amplification",
	"of Damage Amplification",
	"of Charged Shield",
	"of Charged Shield",
	"of Charged Shield",
	"of Charged Shield",
	"of Charged Shield",
	"of Frozen Armor",
	"of Frozen Armor",
	"of Frozen Armor",
	"of Frozen Armor",
	"of Frozen Armor",
	"of Static Field",
	"of Static Field",
	"of Static Field",
	"of Static Field",
	"of Static Field",
	"of Frost Shield",
	"of Frost Shield",
	"of Frost Shield",
	"of Frost Shield",
	"of Frost Shield",
	"of Fire Shield",
	"of Fire Shield",
	"of Fire Shield",
	"of Fire Shield",
	"of Fire Shield",
	"of Meteor Shower",
	"of Meteor Shower",
	"of Meteor Shower",
	"of Meteor Shower",
	"of Meteor Shower",
	"of Shiver Armor",
	"of Shiver Armor",
	"of Shiver Armor",
	"of Shiver Armor",
	"of Shiver Armor",
	"of Hydra Shield",
	"of Hydra Shield",
	"of Hydra Shield",
	"of Hydra Shield",
	"of Hydra Shield",
	"of Enchantment",
	"of Enchantment",
	"of Teleportation",
	"of Teleportation",
	"of Shiver Armor",
	"of Shiver Armor",
	"of Amplify Damage",
	"of Amplify Damage",
	"of Dim Vision",
	"of Dim Vision",
	"of Clay Golem Summoning",
	"of Clay Golem Summoning",
	"of Lower Resistance",
	"of Lower Resistance",
	"of Battle Orders",
	"of Battle Orders",
	"of Fade",
	"of Fade",
	"of Venom",
	"of Venom",
	"of the Tank",
	"of Mastery",
	"of Grand Mastery",
	"of the Rainbow",
	"of the Rainbow",
	"of the Rainbow",
	"of the Rainbow",
	"of Replenishment",
	"of Replenishment",
	"of Targeting",
	"of Mauling",
	"of Wounding",
	"of the Psyche",
	"of Sorcery",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Skill Master",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"Charms",
	"of Puncturing",
	"of Puncturing",
	"of Puncturing",
	"of Puncturing",
	"of Puncturing",
	"of Puncturing",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Thorns",
	"of Frost",
	"of the Icicle",
	"of the Glacier",
	"of Winter",
	"of Frost",
	"of the Icicle",
	"of the Glacier",
	"of Winter",
	"of Frost",
	"of the Icicle",
	"of the Glacier",
	"of Winter",
	"of Flame",
	"of Fire",
	"of Burning",
	"of Incineration",
	"of Flame",
	"of Fire",
	"of Burning",
	"of Incineration",
	"of Flame",
	"of Fire",
	"of Burning",
	"of Incineration",
	"of Shock",
	"of Lightning",
	"of Thunder",
	"of Storms",
	"of Shock",
	"of Lightning",
	"of Thunder",
	"of Storms",
	"of Shock",
	"of Lightning",
	"of Thunder",
	"of Storms",
	"of Blight",
	"of Venom",
	"of Pestilence",
	"of Anthrax",
	"of Blight",
	"of Venom",
	"of Pestilence",
	"of Anthrax",
	"of Blight",
	"of Venom",
	"of Pestilence",
	"of Anthrax",
	"of Craftsmanship",
	"of Quality",
	"of Maiming",
	"of Craftsmanship",
	"of Quality",
	"of Maiming",
	"of Craftsmanship",
	"of Quality",
	"of Maiming",
	"of Balance",
	"of Balance",
	"of Balance",
	"of Balance",
	"of Balance",
	"of Balance",
	"of Inertia",
	"of Inertia",
	"of Inertia",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Greed",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Fortune",
	"of Life",
	"of Life",
	"of Life",
	"of Substinence",
	"of Substinence",
	"of Substinence",
	"of Vita",
	"of Vita",
	"of Vita",
	"of Life",
	"of Life",
	"of Life",
	"of Substinence",
	"of Substinence",
	"of Vita",
	"of Vita",
	"of Life",
	"of Life",
	"of Substinence",
	"of Vita",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Strength",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of Dexterity",
	"of the Hero",
	"of the Hero",
	"of the Hero",
	"of the Rogue",
	"of the Rogue",
	"of the Rogue",
	"of the Rogue",
	"of the Rogue",
	"of the Rogue",
	"of the Collector",
	"of the Collector",
	"of the Collector",
	"of the Collector",
	"of the Collector",
	"of the Collector",
	"of the Valiant",
	"of the Valiant",
	"of the Valiant",
	"of the Wicked",
	"of the Wicked",
	"of the Wicked",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Angel",
	"of the Lurker",
	"of the Lurker",
	"of the Lurker",
	"of the Lurker",
	"of the Lurker",
	"of the Lurker",
	"Jewels",
	"of Faith",
	"of Stoicism",
	"of Desire",
	"of Malice",
	"of Fervor",
	"of Frigidity",
	"of the Icicle",
	"of the Glacier",
	"of Passion",
	"of Fire",
	"of Burning",
	"of Ennui",
	"of Lightning",
	"of Thunder",
	"of Ire",
	"of Wrath",
	"of Carnage",
	"of Joyfulness",
	"of Bliss",
	"of Envy",
	"of Blight",
	"of Venom",
	"of Pestilence",
	"of Daring",
	"of Daring",
	"of Daring",
	"of Truth",
	"of Honor",
	"of Avarice",
	"of Prosperity",
	"of Knowledge",
	"of Knowledge",
	"of Knowledge",
	"of Spirit",
	"of Spirit",
	"of Spirit",
	"of Freedom",
	"of Virility",
	"of Virility",
	"of Virility",
	"of the Werewolf",
	"of the Werewolf",
	"of the Werewolf",
	"of the Werewolf",
	"of the Werewolf",
	"of the Wererat",
	"of the Wererat",
	"of the Wererat",
	"of the Wererat",
	"of the Wererat",
	"of the Werebear",
	"of the Werebear",
	"of the Werebear",
	"of the Werebear",
	"of the Werebear",
	"of the Weretiger",
	"of the Weretiger",
	"of the Weretiger",
	"of the Weretiger",
	"of the Weretiger",
	"of Shielding",
	"Quivers",
	"of Wrath",
	"of Smiting",
	"of Molasses",
	"of Piercing",
	"of Plenty",
	"of Wrath",
	"of Smiting",
	"of Molasses",
	"of Piercing",
	"of Plenty",
	"of Wrath",
	"of Smiting",
	"of Molasses",
	"of Piercing",
	"of Plenty",
	"of Wrath",
	"of Smiting",
	"of Molasses",
	"of Piercing",
	"of Plenty",
	"ChitNor",
	"ChitNM",
	"ChitHell",
	"RndStone",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"Added",
	"of Skill Master",
	"of Aurora",
	"of Aurora",
	"of Aurora",
	"of Static Field",
	"of Aurora",
	"of Damage",
	"of Damage",
	"of Damage",
	"of Damage",
	"of Explosive Arrow",
	"of Explosive Arrow",
	"of Magic Arrow",
	"of Magic Arrow",
	"of Sentence",
	"of Sentence",
	"of Sentence",
	"of Sentence",
	"of Emphasis",
	"of Emphasis",
	"of Emphasis",
	"of Emphasis",
	"of Emphasis",
	"of Emphasis",
	"of Command",
};

const char *SuffixDetails[ITEM_SUFFIX_COUNT] = 
{
	"",
	"red-dmg (1-2)",
	"red-dmg (3-4)",
	"red-dmg (5-6)",
	"red-dmg (7-14)",
	"red-dmg (15-24)",
	"red-dmg (25-50)",
	"red-mag (1-2)",
	"red-mag (3-4)",
	"red-mag (5-12)",
	"red-mag (13-24)",
	"ac-miss (50-100)",
	"ac-hth (50-100)",
	"ac-miss (100-200)",
	"ac-hth (100-200)",
	"ignore-ac (1-1)",
	"dmg-ac (-20--50)",
	"dmg-ac (-51--120)",
	"dmg-ac (-121--200)",
	"dmg-ac",
	"thorns (10-40)",
	"thorns (41-80)",
	"thorns (81-160)",
	"thorns (161-320)",
	"swing1 (10-10)",
	"swing2 (20-20)",
	"swing2 (30-30)",
	"swing3 (40-40)",
	"block (10-10) block2 (15-15)",
	"block (20-20) block2 (30-30)",
	"cast1 (10-10)",
	"cast3 (15-15)",
	"cast3 (20-20)",
	"cold-min (1-2) cold-max (3-11) cold-len (50-50)",
	"cold-min (3-5) cold-max (12-35) cold-len (75-75)",
	"cold-min (6-10) cold-max (36-70) cold-len (100-100)",
	"cold-min (11-20) cold-max (71-140) cold-len (150-150)",
	"cold-min (21-40) cold-max (141-280) cold-len (200-200)",
	"fire-min (1-3) fire-max (4-12)",
	"fire-min (4-7) fire-max (13-37)",
	"fire-min (8-15) fire-max (38-75)",
	"fire-min (16-30) fire-max (76-150)",
	"fire-min (31-60) fire-max (151-300)",
	"ltng-min (1-1) ltng-max (5-16)",
	"ltng-min (1-1) ltng-max (17-50)",
	"ltng-min (1-1) ltng-max (51-100)",
	"ltng-min (1-1) ltng-max (101-200)",
	"ltng-min (1-1) ltng-max (201-400)",
	"50 dmg-pois (103-103)",
	"75 dmg-pois (137-137)",
	"100 dmg-pois (205-205)",
	"125 dmg-pois (328-328)",
	"150 dmg-pois (547-547)",
	"dmg-min (1-1)  20",
	"dmg-min (2-3)  40",
	"dmg-min (4-6)  80",
	"dmg-min (7-12)  160",
	"dmg-min (13-20)  320",
	"dmg-max (1-2)",
	"dmg-max (3-4)",
	"dmg-max (5-7)",
	"dmg-max (8-12)",
	"dmg-max (13-20)",
	"dmg-max (21-30)",
	"dmg-max (31-40)",
	"dmg-max (41-55)",
	"dmg-max (56-80)",
	"res-pois-len (25-25)",
	"res-pois-len (50-50)",
	"res-pois-len (75-75)",
	"half-freeze (1-1)",
	"balance1 (10-10)",
	"balance2 (17-17)",
	"balance3 (24-24)",
	"move1 (10-10)",
	"move2 (20-20)",
	"move3 (30-30)",
	"move3 (40-40)",
	"move3 (30-30) stamdrain (80-90)",
	"regen (3-5)",
	"regen (6-10)",
	"regen (11-15)",
	"noheal (1-1)",
	"gold% (10-20)",
	"gold% (21-40)",
	"gold% (41-60)",
	"mag% (7-15)",
	"mag% (16-30)",
	"mag% (31-45)",
	"mag% (16-30) gold% (21-40)",
	"ease (-20--20)",
	"ease (-30--30)",
	"ease (-40--40)",
	"knock (1-1)",
	"light (1-1) 2 att/lvl",
	"light (3-3) 6 att/lvl",
	"light (5-5) 10 att/lvl",
	"hp (1-5)",
	"hp (6-10)",
	"hp (11-20)",
	"hp (21-30)",
	"hp (31-40)",
	"hp (41-60)",
	"hp (61-80)",
	"hp (81-100)",
	"lifesteal (4-6)",
	"lifesteal (7-9)",
	"lifesteal (10-12)",
	"manasteal (4-6)",
	"manasteal (7-9)",
	"manasteal (10-12)",
	"str (1-3)",
	"str (4-6)",
	"str (7-10)",
	"str (11-15)",
	"str (16-20)",
	"str (21-30)",
	"dex (1-3)",
	"dex (4-6)",
	"dex (7-10)",
	"dex (11-15)",
	"dex (16-20)",
	"dex (21-30)",
	"enr (1-3)",
	"enr (4-6)",
	"enr (7-10)",
	"enr (11-15)",
	"enr (16-20)",
	"enr (21-30)",
	"res-all (10-10) res-all-max (2-4)",
	"res-all (15-15) res-all-max (3-6)",
	"res-all (20-20) res-all-max (4-8)",
	"res-all (25-25) res-all-max (5-10)",
	"3 rep-dur",
	"5 rep-dur",
	"5 rep-quant",
	"10 rep-quant",
	"indestruct",
	"6 hp/lvl",
	"6 mana/lvl",
	"3 hp/lvl 3 mana/lvl",
	"4 str/lvl",
	"4 dex/lvl",
	"2 str/lvl 2 dex/lvl",
	"4 res-cold/lvl",
	"4 res-fire/lvl",
	"4 res-ltng/lvl",
	"4 res-pois/lvl",
	"2 res-cold/lvl 2 res-fire/lvl 2 res-ltng/lvl",
	"dmg-demon (125-125) dmg-undead (125-125)",
	"dmg-demon (150-150) dmg-undead (150-150)",
	"freeze (1-1) nofreeze (1-1)",
	"hit-skill 6% CtC Lvl 5 Fire Ball",
	"hit-skill 7% CtC Lvl 10 Fire Ball",
	"hit-skill 9% CtC Lvl 15 Fire Ball",
	"hit-skill 10% CtC Lvl 20 Fire Ball",
	"hit-skill 12% CtC Lvl 25 Fire Ball",
	"hit-skill 6% CtC Lvl 8 Lightning",
	"hit-skill 7% CtC Lvl 15 Lightning",
	"hit-skill 9% CtC Lvl 20 Lightning",
	"hit-skill 10% CtC Lvl 25 Lightning",
	"hit-skill 12% CtC Lvl 30 Lightning",
	"hit-skill 6% CtC Lvl 5 Chain Lightning",
	"hit-skill 7% CtC Lvl 10 Chain Lightning",
	"hit-skill 9% CtC Lvl 15 Chain Lightning",
	"hit-skill 10% CtC Lvl 20 Chain Lightning",
	"hit-skill 12% CtC Lvl 25 Chain Lightning",
	"hit-skill 6% CtC Lvl 5 Glacial Spike",
	"hit-skill 7% CtC Lvl 10 Glacial Spike",
	"hit-skill 9% CtC Lvl 15 Glacial Spike",
	"hit-skill 10% CtC Lvl 20 Glacial Spike",
	"hit-skill 12% CtC Lvl 25 Glacial Spike",
	"hit-skill 6% CtC Lvl 5 ctcFrozen Orb",
	"hit-skill 7% CtC Lvl 10 ctcFrozen Orb",
	"hit-skill 9% CtC Lvl 15 ctcFrozen Orb",
	"hit-skill 10% CtC Lvl 20 ctcFrozen Orb",
	"hit-skill 12% CtC Lvl 25 ctcFrozen Orb",
	"hit-skill 6% CtC Lvl 8 Ice Bolt",
	"hit-skill 7% CtC Lvl 15 Ice Bolt",
	"hit-skill 9% CtC Lvl 20 Ice Bolt",
	"hit-skill 10% CtC Lvl 25 Ice Bolt",
	"hit-skill 12% CtC Lvl 30 Ice Bolt",
	"hit-skill 6% CtC Lvl 5 Nova",
	"hit-skill 7% CtC Lvl 10 Nova",
	"hit-skill 9% CtC Lvl 15 Nova",
	"hit-skill 10% CtC Lvl 20 Nova",
	"hit-skill 12% CtC Lvl 25 Nova",
	"hit-skill 5% CtC Lvl 6 ctcMeteor",
	"hit-skill 6% CtC Lvl 12 ctcMeteor",
	"hit-skill 7% CtC Lvl 18 ctcMeteor",
	"hit-skill 8% CtC Lvl 24 ctcMeteor",
	"hit-skill 9% CtC Lvl 30 ctcMeteor",
	"hit-skill 6% CtC Lvl 5 ctcBlizzard",
	"hit-skill 7% CtC Lvl 10 ctcBlizzard",
	"hit-skill 9% CtC Lvl 15 ctcBlizzard",
	"hit-skill 10% CtC Lvl 20 ctcBlizzard",
	"hit-skill 12% CtC Lvl 25 ctcBlizzard",
	"hit-skill 5% CtC Lvl 4 Amplify Damage",
	"hit-skill 6% CtC Lvl 5 Amplify Damage",
	"hit-skill 7% CtC Lvl 6 Amplify Damage",
	"hit-skill 8% CtC Lvl 7 Amplify Damage",
	"hit-skill 9% CtC Lvl 8 Amplify Damage",
	"gethit-skill 6% CtC Lvl 8 Charged Bolt",
	"gethit-skill 7% CtC Lvl 15 Charged Bolt",
	"gethit-skill 9% CtC Lvl 20 Charged Bolt",
	"gethit-skill 10% CtC Lvl 25 Charged Bolt",
	"gethit-skill 12% CtC Lvl 30 Charged Bolt",
	"gethit-skill 6% CtC Lvl 5 Frozen Armor",
	"gethit-skill 7% CtC Lvl 10 Frozen Armor",
	"gethit-skill 9% CtC Lvl 15 Frozen Armor",
	"gethit-skill 10% CtC Lvl 20 Frozen Armor",
	"gethit-skill 12% CtC Lvl 25 Frozen Armor",
	"gethit-skill 6% CtC Lvl 5 Static Field",
	"gethit-skill 7% CtC Lvl 10 Static Field",
	"gethit-skill 9% CtC Lvl 15 Static Field",
	"gethit-skill 10% CtC Lvl 20 Static Field",
	"gethit-skill 12% CtC Lvl 25 Static Field",
	"gethit-skill 6% CtC Lvl 5 Frost Nova",
	"gethit-skill 7% CtC Lvl 10 Frost Nova",
	"gethit-skill 9% CtC Lvl 15 Frost Nova",
	"gethit-skill 10% CtC Lvl 20 Frost Nova",
	"gethit-skill 12% CtC Lvl 25 Frost Nova",
	"gethit-skill 6% CtC Lvl 5 Nova",
	"gethit-skill 7% CtC Lvl 10 Nova",
	"gethit-skill 9% CtC Lvl 15 Nova",
	"gethit-skill 10% CtC Lvl 20 Nova",
	"gethit-skill 12% CtC Lvl 25 Nova",
	"gethit-skill 6% CtC Lvl 5 Shiver Armor",
	"gethit-skill 7% CtC Lvl 10 Shiver Armor",
	"gethit-skill 9% CtC Lvl 15 Shiver Armor",
	"gethit-skill 10% CtC Lvl 20 Shiver Armor",
	"gethit-skill 12% CtC Lvl 25 Shiver Armor",
	"gethit-skill 6% CtC Lvl 5 Chilling Armor",
	"gethit-skill 7% CtC Lvl 10 Chilling Armor",
	"gethit-skill 9% CtC Lvl 15 Chilling Armor",
	"gethit-skill 10% CtC Lvl 20 Chilling Armor",
	"gethit-skill 12% CtC Lvl 25 Chilling Armor",
	"gethit-skill 6% CtC Lvl 5 ctcHydra",
	"gethit-skill 7% CtC Lvl 10 ctcHydra",
	"gethit-skill 9% CtC Lvl 15 ctcHydra",
	"gethit-skill 10% CtC Lvl 20 ctcHydra",
	"gethit-skill 12% CtC Lvl 25 ctcHydra",
	"Lvl 10 Enchant (30 Charges)",
	"Lvl 15 Enchant (45 Charges)",
	"Lvl 6 Teleport (40 Charges)",
	"Lvl 9 Teleport (60 Charges)",
	"Lvl 10 Chilling Armor (30 Charges)",
	"Lvl 15 Chilling Armor (45 Charges)",
	"Lvl 6 Amplify Damage (40 Charges)",
	"Lvl 9 Amplify Damage (60 Charges)",
	"Lvl 6 Dim Vision (40 Charges)",
	"Lvl 9 Dim Vision (60 Charges)",
	"Lvl 16 Clay Golem (30 Charges)",
	"Lvl 24 Clay Golem (45 Charges)",
	"Lvl 6 Lower Resist (40 Charges)",
	"Lvl 9 Lower Resist (60 Charges)",
	"Lvl 10 Battle Orders (30 Charges)",
	"Lvl 15 Battle Orders (45 Charges)",
	"Lvl 10 Fade (30 Charges)",
	"Lvl 15 Fade (45 Charges)",
	"Lvl 10 Venom (30 Charges)",
	"Lvl 15 Venom (45 Charges)",
	"red-dmg% (8-15) 16 thorns/lvl ac% (50-200)",
	"dmg-ac (-10--10) swing2 (10-10) dmg% (75-75)",
	"dmg-ac (-15--15) swing2 (20-20) dmg% (100-100)",
	"cold-max (50-75) fire-max (50-75) ltng-max (50-75)",
	"cold-max (76-125) fire-max (76-125) ltng-max (76-125)",
	"cold-max (126-175) fire-max (126-175) ltng-max (126-175)",
	"cold-max (176-250) fire-max (176-250) ltng-max (176-250)",
	"regen (25-25) regen-stam (25-25)",
	"regen (25-25) regen-stam (25-25)",
	"deadly (15-15)",
	"crush (10-10)",
	"openwounds (20-20)",
	"regen-mana (10-15)",
	"regen-mana (20-30)",
	"Dopplezon oskill (1-8)",
	"Multiple Shot oskill (1-4)",
	"Killer Scythe oskill (1-12)",
	"Dodge oskill (1-8)",
	"Slow Missiles oskill (1-8) Inner Sight oskill (1-8)",
	"Freezing Arrow oskill (1-12)",
	"Exploding Arrow oskill (1-12)",
	"Guided Arrow oskill (1-12)",
	"SFire Wall oskill (1-12)",
	"Lightning Strike oskill (1-12)",
	"Strafe oskill (1-12)",
	"Pierce oskill (1-8)",
	"Valkyrie oskill (1-8)",
	"Frozen Armor oskill (1-16)",
	"Teleport oskill (1-4)",
	"Enchant oskill (1-4)",
	"Nova oskill (1-16)",
	"Hydra oskill (1-16)",
	"Fire Mastery oskill (1-4)",
	"Lightning Mastery oskill (1-4)",
	"Cold Mastery oskill (1-4)",
	"Chain Lightning oskill (1-16)",
	"Frozen Orb oskill (1-16)",
	"Bone Armor oskill (1-16)",
	"Amplify Damage oskill (1-8)",
	"Clay Golem oskill (1-12) Golem Mastery oskill (1-8)",
	"Dim Vision oskill (1-8)",
	"Confuse oskill (1-4)",
	"Raise Skeleton oskill (1-8) Skeleton Mastery oskill (1-8)",
	"BloodGolem oskill (1-12) Golem Mastery oskill (1-8)",
	"Decrepify oskill (1-4)",
	"Bone Spirit oskill (1-16)",
	"FireGolem oskill (1-12) Golem Mastery oskill (1-8)",
	"Raise Skeletal Mage oskill (1-8) Skeleton Mastery oskill (1-8)",
	"Poison Nova oskill (1-16)",
	"Lower Resist oskill (1-4)",
	"SHydra oskill (1-16)",
	"Blessed Aim oskill (1-12)",
	"Sanctuary oskill (1-12)",
	"Defiance oskill (1-16)",
	"Zeal oskill (1-4)",
	"Cleansing oskill (1-16)",
	"Holy Fire oskill (1-16)",
	"Vengeance oskill (1-12)",
	"Holy Freeze oskill (1-16)",
	"Vigor oskill (1-12)",
	"Might oskill (1-16)",
	"Meditation oskill (1-16)",
	"Holy Shock oskill (1-16)",
	"Salvation oskill (1-12)",
	"Fanaticism oskill (1-12)",
	"SSummon Grizzly oskill (1-8)",
	"Sword Mastery oskill (1-4)",
	"Axe Mastery oskill (1-4)",
	"Mace Mastery oskill (1-4)",
	"Spear Mastery oskill (1-4)",
	"Throwing Mastery oskill (1-4)",
	"Pole Arm Mastery oskill (1-4)",
	"Shout oskill (1-12)",
	"Iron Skin oskill (1-4)",
	"Battle Orders oskill (1-12)",
	"War Cry oskill (1-12)",
	"Berserk oskill (1-12)",
	"Whirlwind oskill (1-8)",
	"Natural Resistance oskill (1-4)",
	"Raven oskill (1-12)",
	"Cow Balloon oskill (1-12)",
	"Wearbear oskill (1-8) Shape Shifting oskill (1-8) Maul oskill (1-8)",
	"Plague Poppy oskill (1-8) Cycle of Life oskill (1-8)",
	"Molten Boulder oskill (1-16)",
	"Eruption oskill (1-16)",
	"Oak Sage oskill (1-8) Heart of Wolverine oskill (1-8)",
	"Summon Spirit Wolf oskill (1-12) Summon Fenris oskill (1-12)",
	"Tornado oskill (1-16)",
	"Wearwolf oskill (1-8) Shape Shifting oskill (1-8) Fury oskill (1-8)",
	"Summon Grizzly oskill (1-16)",
	"Cloak of Shadows oskill (1-8)",
	"Tiger Strike oskill (1-12)",
	"Quickness oskill (1-4)",
	"Claw Mastery oskill (1-4)",
	"Fade oskill (1-4)",
	"Shadow Master oskill (1-16)",
	"Royal Strike oskill (1-12)",
	"Shuriken oskill (1-8)",
	"Venom oskill (1-4)",
	"Mind Blast oskill (1-8)",
	"SCold Missiles oskill (1-12)",
	"Defiance aura (1-12)",
	"Cleansing aura (1-12)",
	"Holy Fire T aura (1-12)",
	"Holy Freeze T aura (1-12)",
	"Vigor aura (1-9)",
	"Meditation aura (1-12)",
	"Holy Shock T aura (1-12)",
	"Salvation aura (1-9)",
	"Blessed Aim aura (1-9)",
	"Sanctuary aura (1-9)",
	"Might aura (1-12)",
	"Fanaticism aura (1-9)",
	"UNUSED",
	"dmg-ac (-5--6)",
	"dmg-ac (-7--8)",
	"dmg-ac (-3--4)",
	"dmg-ac (-5--6)",
	"dmg-ac (-1--2)",
	"dmg-ac (-3--4)",
	"thorns (6-15)",
	"thorns (18-30)",
	"thorns (33-45)",
	"thorns (48-60)",
	"thorns (63-90)",
	"thorns (4-10)",
	"thorns (12-20)",
	"thorns (22-30)",
	"thorns (32-40)",
	"thorns (42-60)",
	"thorns (2-5)",
	"thorns (6-10)",
	"thorns (11-15)",
	"thorns (16-20)",
	"thorns (21-30)",
	"cold-len (35-35) cold-min (3-8) cold-max (9-15)",
	"cold-len (35-35) cold-min (9-15) cold-max (16-30)",
	"cold-len (35-35) cold-min (16-24) cold-max (31-45)",
	"cold-len (35-35) cold-min (25-30) cold-max (46-60)",
	"cold-len (25-25) cold-min (2-5) cold-max (6-10)",
	"cold-len (25-25) cold-min (6-10) cold-max (11-20)",
	"cold-len (25-25) cold-min (11-15) cold-max (21-30)",
	"cold-len (25-25) cold-min (16-20) cold-max (31-40)",
	"cold-len (15-15) cold-min (1-3) cold-max (3-5)",
	"cold-len (15-15) cold-min (4-5) cold-max (6-10)",
	"cold-len (15-15) cold-min (6-8) cold-max (11-15)",
	"cold-len (15-15) cold-min (9-10) cold-max (16-20)",
	"fire-min (3-10) fire-max (11-18)",
	"fire-min (11-18) fire-max (19-36)",
	"fire-min (19-29) fire-max (37-54)",
	"fire-min (30-36) fire-max (55-72)",
	"fire-min (2-6) fire-max (7-12)",
	"fire-min (7-12) fire-max (13-24)",
	"fire-min (13-18) fire-max (25-36)",
	"fire-min (19-24) fire-max (37-48)",
	"fire-min (1-4) fire-max (4-6)",
	"fire-min (5-6) fire-max (7-12)",
	"fire-min (7-10) fire-max (13-18)",
	"fire-min (11-12) fire-max (19-24)",
	"ltng-min (1-1) ltng-max (15-30)",
	"ltng-min (1-1) ltng-max (31-60)",
	"ltng-min (1-1) ltng-max (61-115)",
	"ltng-min (1-1) ltng-max (116-150)",
	"ltng-min (1-1) ltng-max (10-20)",
	"ltng-min (1-1) ltng-max (21-40)",
	"ltng-min (1-1) ltng-max (41-70)",
	"ltng-min (1-1) ltng-max (71-100)",
	"ltng-min (1-1) ltng-max (5-10)",
	"ltng-min (1-1) ltng-max (11-20)",
	"ltng-min (1-1) ltng-max (21-35)",
	"ltng-min (1-1) ltng-max (36-50)",
	"75 dmg-pois (105-105)",
	"100 dmg-pois (231-231)",
	"125 dmg-pois (369-369)",
	"150 dmg-pois (513-513)",
	"75 dmg-pois (70-70)",
	"100 dmg-pois (154-154)",
	"125 dmg-pois (246-246)",
	"150 dmg-pois (342-342)",
	"75 dmg-pois (35-35)",
	"100 dmg-pois (77-77)",
	"125 dmg-pois (123-123)",
	"150 dmg-pois (171-171)",
	"dmg-max (1-3)",
	"dmg-max (4-6)",
	"dmg-max (7-9)",
	"dmg-max (1-2)",
	"dmg-max (3-4)",
	"dmg-max (5-6)",
	"dmg-max (1-1)",
	"dmg-max (2-2)",
	"dmg-max (3-3)",
	"balance3 (10-10)",
	"balance3 (15-15)",
	"balance2 (7-7)",
	"balance2 (10-10)",
	"balance1 (3-3)",
	"balance1 (5-5)",
	"move3 (9-9)",
	"move2 (6-6)",
	"move1 (3-3)",
	"gold% (12-15)",
	"gold% (16-21)",
	"gold% (22-30)",
	"gold% (8-10)",
	"gold% (11-14)",
	"gold% (15-20)",
	"gold% (4-5)",
	"gold% (6-7)",
	"gold% (8-10)",
	"mag% (12-15)",
	"mag% (16-21)",
	"mag% (22-30)",
	"mag% (8-10)",
	"mag% (11-14)",
	"mag% (15-20)",
	"mag% (4-5)",
	"mag% (6-7)",
	"mag% (8-10)",
	"hp (3-10)",
	"hp (9-15)",
	"hp (14-20)",
	"hp (21-25)",
	"hp (26-30)",
	"hp (31-35)",
	"hp (36-40)",
	"hp (41-50)",
	"hp (51-60)",
	"hp (2-7)",
	"hp (8-10)",
	"hp (11-14)",
	"hp (15-18)",
	"hp (19-26)",
	"hp (27-33)",
	"hp (34-40)",
	"hp (1-4)",
	"hp (5-10)",
	"hp (11-16)",
	"hp (17-20)",
	"str (3-5)",
	"str (6-8)",
	"str (9-10)",
	"str (11-12)",
	"str (2-4)",
	"str (5-6)",
	"str (7-8)",
	"str (1-2)",
	"str (3-4)",
	"dex (3-5)",
	"dex (6-8)",
	"dex (9-10)",
	"dex (11-12)",
	"dex (2-4)",
	"dex (5-6)",
	"dex (7-8)",
	"dex (1-2)",
	"dex (3-4)",
	"abs-fire (5-7) abs-cold (5-7) abs-ltng (5-7)",
	"abs-fire (3-5) abs-cold (3-5) abs-ltng (3-5)",
	"abs-fire (1-3) abs-cold (1-3) abs-ltng (1-3)",
	"1 mag%/lvl",
	"2 mag%/lvl",
	"3 mag%/lvl",
	"1 mag%/lvl",
	"2 mag%/lvl",
	"1 mag%/lvl",
	"1 gold%/lvl",
	"2 gold%/lvl",
	"3 gold%/lvl",
	"1 gold%/lvl",
	"2 gold%/lvl",
	"1 gold%/lvl",
	"crush (6-6)",
	"crush (4-4)",
	"crush (2-2)",
	"deadly (6-6)",
	"deadly (4-4)",
	"deadly (2-2)",
	"1 hp/lvl",
	"2 hp/lvl",
	"3 hp/lvl",
	"4 hp/lvl",
	"5 hp/lvl",
	"6 hp/lvl",
	"1 hp/lvl",
	"2 hp/lvl",
	"3 hp/lvl",
	"4 hp/lvl",
	"1 hp/lvl",
	"2 hp/lvl",
	"regen (1-2)",
	"regen (3-4)",
	"regen (5-6)",
	"regen (1-2)",
	"regen (3-4)",
	"regen (1-2)",
	"UNUSED",
	"abs-fire (6-12)",
	"abs-ltng (6-12)",
	"abs-cold (6-12)",
	"thorns (100-200)",
	"swing1 (15-30)",
	"cold-min (5-15) cold-max (10-30) cold-len (50-50)",
	"cold-min (16-30) cold-max (31-60) cold-len (50-50)",
	"cold-min (31-60) cold-max (61-120) cold-len (50-50)",
	"fire-min (10-18) fire-max (20-37)",
	"fire-min (19-37) fire-max (38-75)",
	"fire-min (38-75) fire-max (76-150)",
	"ltng-min (1-1) ltng-max (30-60)",
	"ltng-min (1-1) ltng-max (61-120)",
	"ltng-min (1-1) ltng-max (121-240)",
	"dmg-max (1-6)",
	"dmg-max (7-12)",
	"dmg-max (13-24)",
	"dmg-min (1-8)",
	"dmg-min (5-18)",
	"pois-min (204-204) pois-max (204-204) pois-len (25-25)",
	"pois-min (274-274) pois-max (274-274) pois-len (50-50)",
	"pois-min (410-410) pois-max (410-410) pois-len (75-75)",
	"pois-min (656-656) pois-max (656-656) pois-len (100-100)",
	"dex (1-8)",
	"dex (9-16)",
	"dex (17-24)",
	"balance1 (15-15)",
	"regen (3-16)",
	"gold% (10-40)",
	"mag% (5-20)",
	"enr (1-8)",
	"enr (9-16)",
	"enr (17-24)",
	"hp (3-16)",
	"hp (17-32)",
	"hp (33-64)",
	"ease (-15--30)",
	"str (1-8)",
	"str (9-16)",
	"str (17-24)",
	"1 str/lvl",
	"2 str/lvl",
	"3 str/lvl",
	"4 str/lvl",
	"5 str/lvl",
	"1 dex/lvl",
	"2 dex/lvl",
	"3 dex/lvl",
	"4 dex/lvl",
	"5 dex/lvl",
	"1 vit/lvl",
	"2 vit/lvl",
	"3 vit/lvl",
	"4 vit/lvl",
	"5 vit/lvl",
	"1 enr/lvl",
	"2 enr/lvl",
	"3 enr/lvl",
	"4 enr/lvl",
	"5 enr/lvl",
	"res-all (7-12) res-all-max (2-2)",
	"UNUSED",
	"dmg-demon (25-25)",
	"dmg-undead (25-25)",
	"slow (10-10)",
	"pierce (10-10)",
	"50 stack (50-50)",
	"dmg-demon (50-50)",
	"dmg-undead (50-50)",
	"slow (15-15)",
	"pierce (15-15)",
	"100 stack (100-100)",
	"dmg-demon (75-75)",
	"dmg-undead (75-75)",
	"slow (20-20)",
	"pierce (20-20)",
	"150 stack (150-150)",
	"dmg-demon (100-100)",
	"dmg-undead (100-100)",
	"slow (25-25)",
	"pierce (25-25)",
	"200 stack (200-200)",
	"randomize (1-120)",
	"randomize (1-120)",
	"randomize (1-120)",
	"randomize (1-511)",
	"Holy Fire H aura (1-6)",
	"Holy Freeze H aura (1-6)",
	"Holy Shock H aura (1-6)",
	"UNUSED",
	"Poison Mastery oskill (1-4)",
	"Cancel Cres aura (1-1)",
	"Super Salvation aura (1-1)",
	"Poverty aura (1-1)",
	"Static Field gethit-skill (33-33) Static Field hit-skill (33-33)",
	"Cancel Fres aura (1-1)",
	"dmg% (10-10)",
	"dmg% (15-15)",
	"dmg% (20-20)",
	"dmg% (20-20)",
	"explosivearrow (5-10)",
	"explosivearrow (11-16)",
	"magicarrow (9-16)",
	"magicarrow (17-24)",
	"pierce-fire (1-3)",
	"pierce-cold (1-3)",
	"pierce-ltng (1-3)",
	"pierce-pois (1-3)",
	"extra-fire (2-4)",
	"extra-cold (2-4)",
	"extra-ltng (2-4)",
	"extra-pois (2-4)",
	"extra-mag2 (1-3)",
	"extra-wind (1-3)",
	"extra-summ (4-8)",
};
#endif